# Generated by Django 5.2.7 on 2026-01-31 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada (+)'), ('SALIDA', 'Salida (-)')], max_length=10),
        ),
    ]
